# Generated by Django 4.2.3 on 2023-10-16 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='Заголовок', max_length=255)),
                ('body', models.TextField(default='Здесь должен быть текст')),
                ('mainPic', models.ImageField(upload_to='user_images')),
                ('postRate', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='bb.PostCategory', to='bb.category'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Картинка'), ('V', 'Видео'), ('F', 'Файл')], default='P', max_length=1)),
                ('media', models.FileField(upload_to='user_files')),
                ('toPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cTime', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(default='Комментарий')),
                ('status', models.IntegerField(default=0)),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('toPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb.post')),
            ],
        ),
    ]
