# Generated by Django 4.2.2 on 2023-10-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0002_media_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='descr',
            field=models.TextField(default='Описание файла'),
        ),
    ]
