# Generated by Django 4.2.2 on 2023-10-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0003_media_descr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='cbody',
        ),
    ]
