# Generated by Django 4.2.3 on 2023-10-22 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0004_rename_body_comment_cbody'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cTime', models.DateTimeField(auto_now_add=True)),
                ('rbody', models.TextField(default='Ответ на комментарий')),
                ('toComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb.comment')),
            ],
        ),
    ]
