# Generated by Django 4.2.3 on 2023-10-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0006_remove_media_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='title',
            field=models.CharField(default='Заголовок', max_length=255),
        ),
    ]
